version: '2'
services:
  web:
    build: .
    ports:
      - "80:5000"
    volumes:
      - ./:/opt/pets-api
    links:
      - db:mongodb
    container_name: pets_api_web_1
    depends_on:
      - db
  db:
    image: mongo:3.0.2
    container_name: pets_api_db_1
